<?php /** @var \KingPalm\Adult\Block\Popup $block */ $b = $block; ?>
<div class='df-hidden kingpalm kingpalm-adult-popup'>
	<div class='kp-internal'>
		<img src='<?php echo $this->getViewFileUrl('images/blk-logo.png'); ?>'/>
		<h4>You must be 18 years old to visit this site</h4>
		<ul>
			<li>Adult signature required upon delivery.</li>
			<li>All products for tobacco and legal herbs use only.</li>
		</ul>
		<div class='verify'>
			<h4>Please verify your age:</h4>
			<?= df_cc_n(
				$b->cb('18', 'I am at least 18 years old'), $b->cb('remember', 'Remember me')
			) ?>
		</div>
		<button class='action primary'>
			<span>Enter</span>
		</button><span>or</span><a href='https://google.com'>Exit</a>
	</div>
</div>
<?= df_js_x('.kingpalm-adult-popup', $b); ?>